version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/work
      - ./datalake:/datalake
    working_dir: /work
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
